# Generated by Django 4.1.7 on 2023-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publicationdate', models.DateField()),
                ('bookdescription', models.CharField(max_length=200)),
                ('checkout', models.BooleanField()),
            ],
        ),
    ]
