# Generated by Django 4.1.7 on 2023-03-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checkedoutuser',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
