# Generated by Django 3.2.18 on 2023-03-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_book_checkedoutuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('published', models.DateField()),
                ('head', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
            ],
        ),
    ]
