# Generated by Django 3.2.17 on 2023-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reserve_id', models.IntegerField()),
                ('username', models.CharField(max_length=15)),
                ('pick_up', models.DateField()),
                ('book_id', models.IntegerField()),
            ],
        ),
    ]
