# Generated by Django 3.2.17 on 2023-03-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_reserve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='Reserve_id',
            new_name='reserve_id',
        ),
    ]
