# Generated by Django 4.1.7 on 2023-03-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_remove_reviews_head_reviews_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='published',
        ),
    ]
